### ISSUE TITLE
recent appcomapt 23.2.0 release makes the timeline view expand to full screen

### ISSUE THREAD

**Issue by rrinav** [vipulasri/Timeline-View#5] opened 2016-02-25 08:01 UTC
As the recyclerView in 23.2, the timeline view expands to full_width, even when we use wrap_content for the container.

**Comment by vipulasri** [comment] 2016-02-25 08:28
@rrinav . Thanx for pointing it out. It will be fixed asap in next release.

**Comment by vipulasri** [comment] 2016-02-25 12:28
@rrinav can you post some screenshot of it?

**Comment by rrinav** [comment] 2016-02-25 13:03
Thanks for your time,

below is the screen shot and my layout of recycler view item

[http://imgur.com/RQnUHDn](url)
[http://imgur.com/bggxNhG](url)

I tried match parent, wrap parent and also manually setting as 100dp just to test

    <LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:orientation="horizontal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="top">
        <TextView
            android:id="@+id/tv_panic_btn_event_time"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            tools:text="5:15:30\nPM"
            android:gravity="center"

            android:padding="16dp"/>

        <com.vipul.hp_hp.timelineview.TimelineView
            android:id="@+id/time_marker"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingTop="30dp"
            android:paddingBottom="30dp"
            android:paddingLeft="10dp"
            android:paddingRight="10dp"
            app:marker_size="16dp"
            app:line_size="2dp"
            app:line="@color/divider"/>

        <TextView
            android:id="@+id/tv_panic_btn_event_desc"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            tools:text="Event"
            android:layout_marginLeft="16dp"
            android:layout_marginStart="16dp"
            android:layout_gravity="center_vertical" />

    </LinearLayout>`

**Comment by vipulasri** [comment] 2016-02-25 13:11
can you explain me properly that you are facing problem in width of view or height? As in screenshots it is clear it is having problem in height. 

Refer this issue #4

**Comment by rrinav** [comment] 2016-02-25 14:27
I am having problem with height.
Actually there is huge space between each recycler view items.

if I use match_parent the tine is drawn from top to bottom, but there is still huge space between each item just like issues #4 

I am unable to remove extra spacing between each item

**Comment by vipulasri** [comment] 2016-02-25 14:30
@rrinav just want to confirm are you using RecyclerView? 
and try another solution by removing `android:gravity="top"` from parent `LinearLayout`

**Comment by rrinav** [comment] 2016-02-25 14:36
yes I am using RecyclerView with 
    ```android:layout_width="match_parent"```
    ```android:layout_height="match_parent"```

I tried removing ```android:gravity="top"``` but it's still the same

**Comment by vipulasri** [comment] 2016-02-25 14:39
@rrinav I am also using new RecyclerView v23.2.0 but i am not facing any issues as you are. I would recommend checking and removing TimelineView from your layout and rebuilding it and ensure that this problem remains or not.

**Comment by rrinav** [comment] 2016-02-25 14:48
I'll try to rebuild and look into more detail and report back here.
Thanks for your time

**Comment by vidia** [comment] 2016-03-23 23:08
This seems to be an issue with that update to the RecyclerView and not specific to this library. I say that because in a few og my implementations of RecyclerViews I ran into the same height issues. 

There might be something the library can do to avoid this, but its probably not a bug specific to the library.

**Closed** 2016-03-24 03:11 UTC
